//! Deterministic generation for the canonical Positron v1 public interface.

use std::fs;
use std::path::Path;

use crate::error::XtaskError;

const SOURCE: &str = "api/positron/v1/positron.proto";
const GENERATED_RUST: &str = "crates/positron-api/src/generated.rs";
const SCHEMA_DIGEST: &str = "api/positron/v1/schema.sha256";
const OPENAPI: &str = "api/positron/v1/openapi.json";
const HTTP_MAPPING: &str = "api/positron/v1/http.json";

/// Regenerates every checked artifact owned by the canonical API definition.
pub(crate) fn generate(root: &Path) -> Result<(), XtaskError> {
    let source_path = root.join(SOURCE);
    let source = fs::read_to_string(&source_path)
        .map_err(|source| XtaskError::io(format!("read {}", source_path.display()), source))?;
    validate_source(&source_path, &source)?;
    let digest = sha256_hex(source.as_bytes());

    write_generated(root, GENERATED_RUST, &generated_rust(&digest))?;
    write_generated(root, SCHEMA_DIGEST, &format!("{digest}\n"))?;
    write_generated(root, OPENAPI, &openapi(&digest))?;
    write_generated(root, HTTP_MAPPING, &http_mapping(&digest))?;
    Ok(())
}

fn validate_source(path: &Path, source: &str) -> Result<(), XtaskError> {
    for required in [
        "syntax = \"proto3\";",
        "package positron.v1;",
        "service CapabilityService",
        "rpc Negotiate(CapabilityRequest) returns (CapabilityResponse);",
        "enum CapabilityAvailability",
        "enum RetryClass",
        "enum CompletionState",
        "message PublicError",
    ] {
        if !source.contains(required) {
            return Err(XtaskError::invalid_path(
                path,
                format!("canonical API definition is missing required declaration `{required}`"),
            ));
        }
    }
    Ok(())
}

fn write_generated(root: &Path, relative: &str, contents: &str) -> Result<(), XtaskError> {
    let path = root.join(relative);
    if fs::read_to_string(&path).ok().as_deref() == Some(contents) {
        return Ok(());
    }
    fs::write(&path, contents)
        .map_err(|source| XtaskError::io(format!("write {}", path.display()), source))
}

fn generated_rust(digest: &str) -> String {
    format!(
        r###"//! Generated from `api/positron/v1/positron.proto`; do not edit.

/// The one public API major version generated by this artifact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiVersion {{
    /// Canonical Release 1 API package.
    V1,
}}

impl ApiVersion {{
    /// Returns the wire major version.
    #[must_use]
    pub const fn major(self) -> u32 {{
        match self {{
            Self::V1 => 1,
        }}
    }}
}}

/// The stable SHA-256 identity of the canonical API definition.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SchemaDigest(&'static str);

impl SchemaDigest {{
    /// Returns the digest embedded by deterministic generation.
    #[must_use]
    pub const fn canonical() -> Self {{
        Self("{digest}")
    }}

    /// Returns the lowercase hexadecimal digest value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {{
        self.0
    }}
}}

/// The closed availability truth returned by capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityAvailability {{
    /// The requested API package is implemented by this server.
    Implemented,
    /// A known capability is not available in this server state.
    Unavailable,
    /// The server does not support the requested capability.
    Unsupported,
    /// The request requires an API package this server cannot interpret.
    VersionIncompatible,
}}

/// The closed retry classification attached to a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RetryClass {{
    /// Retrying the same request cannot change the outcome.
    Never,
    /// The caller may retry after an owner-directed bounded backoff.
    AfterBackoff,
    /// The caller must first correct its input.
    AfterInputCorrection,
}}

/// The closed completion truth attached to a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CompletionState {{
    /// The request was rejected before work began.
    Rejected,
}}

/// Stable public error codes for the generated capability foundation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiErrorCode {{
    /// The requested API major has no compatible handler.
    UnsupportedApiVersion,
}}

/// A non-secret semantic location for a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiFailureSource {{
    /// API package negotiation rejected the request.
    CapabilityNegotiation,
}}

/// A closed typed public failure with no caller-controlled diagnostic text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ApiError {{
    code: ApiErrorCode,
    retry_class: RetryClass,
    completion_state: CompletionState,
    source: ApiFailureSource,
}}

impl ApiError {{
    const fn unsupported_api_version() -> Self {{
        Self {{
            code: ApiErrorCode::UnsupportedApiVersion,
            retry_class: RetryClass::Never,
            completion_state: CompletionState::Rejected,
            source: ApiFailureSource::CapabilityNegotiation,
        }}
    }}

    /// Returns the stable public code.
    #[must_use]
    pub const fn code(self) -> ApiErrorCode {{
        self.code
    }}

    /// Returns the typed retry classification.
    #[must_use]
    pub const fn retry_class(self) -> RetryClass {{
        self.retry_class
    }}

    /// Returns whether the rejected request performed any work.
    #[must_use]
    pub const fn completion_state(self) -> CompletionState {{
        self.completion_state
    }}

    /// Returns the safe semantic failure location.
    #[must_use]
    pub const fn source(self) -> ApiFailureSource {{
        self.source
    }}
}}

/// Generated wire request for one API-major capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityRequest {{
    api_major: u32,
}}

impl CapabilityRequest {{
    /// Creates a request for a generated API package.
    #[must_use]
    pub const fn for_version(version: ApiVersion) -> Self {{
        Self {{
            api_major: version.major(),
        }}
    }}

    /// Creates a request carrying an unknown wire major for checked refusal.
    #[must_use]
    pub const fn unknown(api_major: u32) -> Self {{
        Self {{ api_major }}
    }}
}}

/// Generated typed response for capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityResponse {{
    availability: CapabilityAvailability,
    api_version: ApiVersion,
    schema_digest: SchemaDigest,
    refusal: Option<ApiError>,
}}

impl CapabilityResponse {{
    /// Returns the closed capability availability truth.
    #[must_use]
    pub const fn availability(self) -> CapabilityAvailability {{
        self.availability
    }}

    /// Returns the negotiated public API package.
    #[must_use]
    pub const fn api_version(self) -> ApiVersion {{
        self.api_version
    }}

    /// Returns the generated source identity.
    #[must_use]
    pub const fn schema_digest(self) -> SchemaDigest {{
        self.schema_digest
    }}

    /// Returns a stable refusal when negotiation did not succeed.
    #[must_use]
    pub const fn refusal(self) -> Option<ApiError> {{
        self.refusal
    }}
}}

/// Generated in-memory service boundary for the canonical capability contract.
pub struct CapabilityService;

impl CapabilityService {{
    /// Negotiates one bounded, versioned public API request without ambient state.
    #[must_use]
    pub const fn negotiate(request: CapabilityRequest) -> CapabilityResponse {{
        if request.api_major == ApiVersion::V1.major() {{
            CapabilityResponse {{
                availability: CapabilityAvailability::Implemented,
                api_version: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: None,
            }}
        }} else {{
            CapabilityResponse {{
                availability: CapabilityAvailability::VersionIncompatible,
                api_version: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: Some(ApiError::unsupported_api_version()),
            }}
        }}
    }}
}}
"###
    )
}

fn openapi(digest: &str) -> String {
    format!(
        "{{\n  \"openapi\": \"3.1.0\",\n  \"info\": {{\"title\": \"Positron API\", \"version\": \"v1\", \"x-positron-schema-digest\": \"{digest}\"}},\n  \"paths\": {{\"/v1/capabilities:negotiate\": {{\"post\": {{\"operationId\": \"NegotiateCapabilities\"}}}}}}\n}}\n"
    )
}

fn http_mapping(digest: &str) -> String {
    format!(
        "{{\n  \"schema_digest\": \"{digest}\",\n  \"mappings\": [{{\"rpc\": \"positron.v1.CapabilityService/Negotiate\", \"method\": \"POST\", \"path\": \"/v1/capabilities:negotiate\"}}]\n}}\n"
    )
}

fn sha256_hex(input: &[u8]) -> String {
    let mut state = [
        0x6a09_e667_u32,
        0xbb67_ae85,
        0x3c6e_f372,
        0xa54f_f53a,
        0x510e_527f,
        0x9b05_688c,
        0x1f83_d9ab,
        0x5be0_cd19,
    ];
    let mut padded = input.to_vec();
    let bit_length = (input.len() as u64).wrapping_mul(8);
    padded.push(0x80);
    while padded.len() % 64 != 56 {
        padded.push(0);
    }
    padded.extend_from_slice(&bit_length.to_be_bytes());
    for chunk in padded.chunks_exact(64) {
        let mut words = [0_u32; 64];
        for (slot, bytes) in words.iter_mut().take(16).zip(chunk.chunks_exact(4)) {
            let Ok(bytes) = <&[u8; 4]>::try_from(bytes) else {
                return String::new();
            };
            *slot = u32::from_be_bytes(*bytes);
        }
        for index in 16..64 {
            let Some(&previous_fifteen) = words.get(index - 15) else {
                return String::new();
            };
            let Some(&previous_two) = words.get(index - 2) else {
                return String::new();
            };
            let Some(&previous_sixteen) = words.get(index - 16) else {
                return String::new();
            };
            let Some(&previous_seven) = words.get(index - 7) else {
                return String::new();
            };
            let first = previous_fifteen.rotate_right(7)
                ^ previous_fifteen.rotate_right(18)
                ^ (previous_fifteen >> 3);
            let second = previous_two.rotate_right(17)
                ^ previous_two.rotate_right(19)
                ^ (previous_two >> 10);
            let value = previous_sixteen
                .wrapping_add(first)
                .wrapping_add(previous_seven)
                .wrapping_add(second);
            let Some(slot) = words.get_mut(index) else {
                return String::new();
            };
            *slot = value;
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut h] = state;
        for (word, constant) in words.into_iter().zip(SHA256_CONSTANTS) {
            let choice = (e & f) ^ ((!e) & g);
            let majority = (a & b) ^ (a & c) ^ (b & c);
            let first = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let second = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let temporary_one = h
                .wrapping_add(second)
                .wrapping_add(choice)
                .wrapping_add(constant)
                .wrapping_add(word);
            let temporary_two = first.wrapping_add(majority);
            h = g;
            g = f;
            f = e;
            e = d.wrapping_add(temporary_one);
            d = c;
            c = b;
            b = a;
            a = temporary_one.wrapping_add(temporary_two);
        }
        state[0] = state[0].wrapping_add(a);
        state[1] = state[1].wrapping_add(b);
        state[2] = state[2].wrapping_add(c);
        state[3] = state[3].wrapping_add(d);
        state[4] = state[4].wrapping_add(e);
        state[5] = state[5].wrapping_add(f);
        state[6] = state[6].wrapping_add(g);
        state[7] = state[7].wrapping_add(h);
    }
    state.iter().map(|word| format!("{word:08x}")).collect()
}

const SHA256_CONSTANTS: [u32; 64] = [
    0x428a_2f98,
    0x7137_4491,
    0xb5c0_fbcf,
    0xe9b5_dba5,
    0x3956_c25b,
    0x59f1_11f1,
    0x923f_82a4,
    0xab1c_5ed5,
    0xd807_aa98,
    0x1283_5b01,
    0x2431_85be,
    0x550c_7dc3,
    0x72be_5d74,
    0x80de_b1fe,
    0x9bdc_06a7,
    0xc19b_f174,
    0xe49b_69c1,
    0xefbe_4786,
    0x0fc1_9dc6,
    0x240c_a1cc,
    0x2de9_2c6f,
    0x4a74_84aa,
    0x5cb0_a9dc,
    0x76f9_88da,
    0x983e_5152,
    0xa831_c66d,
    0xb003_27c8,
    0xbf59_7fc7,
    0xc6e0_0bf3,
    0xd5a7_9147,
    0x06ca_6351,
    0x1429_2967,
    0x27b7_0a85,
    0x2e1b_2138,
    0x4d2c_6dfc,
    0x5338_0d13,
    0x650a_7354,
    0x766a_0abb,
    0x81c2_c92e,
    0x9272_2c85,
    0xa2bf_e8a1,
    0xa81a_664b,
    0xc24b_8b70,
    0xc76c_51a3,
    0xd192_e819,
    0xd699_0624,
    0xf40e_3585,
    0x106a_a070,
    0x19a4_c116,
    0x1e37_6c08,
    0x2748_774c,
    0x34b0_bcb5,
    0x391c_0cb3,
    0x4ed8_aa4a,
    0x5b9c_ca4f,
    0x682e_6ff3,
    0x748f_82ee,
    0x78a5_636f,
    0x84c8_7814,
    0x8cc7_0208,
    0x90be_fffa,
    0xa450_6ceb,
    0xbef9_a3f7,
    0xc671_78f2,
];
