use sha2::{Digest, Sha256};
use std::error::Error;
use std::fmt::Write;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn Error>> {
    let schema = "../../api/positron/v1/positron.proto";
    let mapping = "../../api/positron/v1/http.json";
    println!("cargo:rerun-if-changed={schema}");
    println!("cargo:rerun-if-changed={mapping}");
    let mut digest = String::with_capacity(64);
    for byte in Sha256::digest(std::fs::read(schema)?) {
        write!(&mut digest, "{byte:02x}")?;
    }
    println!("cargo:rustc-env=POSITRON_API_SCHEMA_DIGEST={digest}");
    let mut config = prost_build::Config::new();
    config.protoc_executable(protoc_bin_vendored::protoc_bin_path()?);
    for message in ["ApiKeyRequest", "ApiKeyResponse", "KeyDescriptor"] {
        config.type_attribute(
            format!(".positron.v1.{message}"),
            "#[derive(serde::Serialize, serde::Deserialize)] #[serde(deny_unknown_fields)]",
        );
    }
    for enumeration in ["KeyAction", "KeyScope"] {
        config.type_attribute(
            format!(".positron.v1.{enumeration}"),
            "#[derive(serde::Serialize, serde::Deserialize)] #[serde(rename_all = \"snake_case\")]",
        );
    }
    config.field_attribute(
        ".positron.v1.ApiKeyRequest.action",
        "#[serde(with = \"super::action_json\")]",
    );
    config.field_attribute(".positron.v1.ApiKeyRequest.scope", "#[serde(default, skip_serializing_if = \"Option::is_none\", with = \"super::optional_scope_json\")]");
    for field in [
        "principal",
        "expires_at_unix_seconds",
        "expected_generation",
        "idempotency_key",
    ] {
        config.field_attribute(
            format!(".positron.v1.ApiKeyRequest.{field}"),
            "#[serde(default, skip_serializing_if = \"Option::is_none\")]",
        );
    }
    config.field_attribute(
        ".positron.v1.KeyDescriptor.scope",
        "#[serde(with = \"super::scope_json\")]",
    );
    config.skip_debug([".positron.v1.ApiKeyResponse"]);
    let descriptor = PathBuf::from(std::env::var("OUT_DIR")?).join("positron-v1.bin");
    config.file_descriptor_set_path(&descriptor);
    config.compile_protos(&[schema], &["../../api"])?;
    generate_api_key_client(&descriptor, mapping)?;
    Ok(())
}

fn generate_api_key_client(
    descriptor_path: &std::path::Path,
    mapping_path: &str,
) -> Result<(), Box<dyn Error>> {
    use prost::Message;
    let descriptor =
        prost_types::FileDescriptorSet::decode(std::fs::read(descriptor_path)?.as_slice())?;
    let service_exists = descriptor.file.iter().any(|file| {
        file.package.as_deref() == Some("positron.v1")
            && file.service.iter().any(|service| {
                service.name.as_deref() == Some("ApiKeyService")
                    && service.method.iter().any(|method| {
                        method.name.as_deref() == Some("Manage")
                            && method.input_type.as_deref() == Some(".positron.v1.ApiKeyRequest")
                            && method.output_type.as_deref() == Some(".positron.v1.ApiKeyResponse")
                    })
            })
    });
    if !service_exists {
        return Err(
            "ApiKeyService/Manage is missing from the canonical protobuf descriptor".into(),
        );
    }
    let mapping: serde_json::Value = serde_json::from_slice(&std::fs::read(mapping_path)?)?;
    let route = mapping["mappings"]
        .as_array()
        .and_then(|routes| {
            routes
                .iter()
                .find(|route| route["rpc"] == "positron.v1.ApiKeyService/Manage")
        })
        .ok_or("ApiKeyService/Manage is missing from the canonical HTTP mapping")?;
    let path = route["path"]
        .as_str()
        .filter(|path| path.starts_with('/'))
        .ok_or("ApiKeyService/Manage HTTP path is invalid")?;
    let request_limit = route["max_request_bytes"]
        .as_u64()
        .filter(|limit| *limit <= usize::MAX as u64)
        .ok_or("ApiKeyService/Manage request limit is invalid")?;
    let response_limit = route["max_response_bytes"]
        .as_u64()
        .filter(|limit| *limit <= usize::MAX as u64)
        .ok_or("ApiKeyService/Manage response limit is invalid")?;
    let source = format!(
        r#"// Generated by positron-api/build.rs from ApiKeyService/Manage in the canonical
// protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::fs;
use std::time::Duration;

pub struct ApiKeyServiceClient {{
    endpoint: String,
    client: reqwest::blocking::Client,
}}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiKeyServiceClientFailure {{
    AuthenticationRejected,
    StaleGeneration,
    IdempotencyConflict,
    KeyUnavailable,
    AdministrationUnavailable,
    Transport,
}}

impl std::fmt::Display for ApiKeyServiceClientFailure {{
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        formatter.write_str("API-key service request failed")
    }}
}}
impl std::error::Error for ApiKeyServiceClientFailure {{}}

impl ApiKeyServiceClient {{
    pub fn new(transport: super::ApiKeyTransport) -> Result<Self, ApiKeyServiceClientFailure> {{
        let (endpoint, builder) = match transport {{
            super::ApiKeyTransport::Tls {{ endpoint, server_name, trust_file }} => {{
                if server_name.is_empty() || server_name.len() > 253 || !server_name.bytes().all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-' | b':')) {{
                    return Err(ApiKeyServiceClientFailure::Transport);
                }}
                let trust = fs::read(trust_file).map_err(|_| ApiKeyServiceClientFailure::Transport)?;
                let certificate = reqwest::Certificate::from_pem(&trust)
                    .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
                (format!("https://{{server_name}}:{{}}", endpoint.port()), reqwest::blocking::Client::builder().add_root_certificate(certificate))
            }},
            super::ApiKeyTransport::PlaintextOptOut {{ endpoint }} => (format!("http://{{endpoint}}"), reqwest::blocking::Client::builder()),
        }};
        let client = builder
            .connect_timeout(Duration::from_secs(5))
            .timeout(Duration::from_secs(5))
            .no_proxy()
            .build()
            .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        Ok(Self {{ endpoint, client }})
    }}

    pub fn manage(
        &self,
        bearer: &str,
        request: &super::ApiKeyRequest,
    ) -> Result<super::ApiKeyResponse, ApiKeyServiceClientFailure> {{
        let body = request.encode().map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        if body.len() > {request_limit} {{
            return Err(ApiKeyServiceClientFailure::Transport);
        }}
        let url = format!("{{}}{{}}", self.endpoint, {path:?});
        let response = self.client.post(url)
            .bearer_auth(bearer)
            .header(reqwest::header::CONTENT_TYPE, "application/json")
            .body(body)
            .send()
            .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        let status = response.status().as_u16();
        let mut bytes = zeroize::Zeroizing::new(Vec::with_capacity({response_limit}));
        response.take(({response_limit} + 1) as u64)
            .read_to_end(&mut bytes)
            .map_err(|_| ApiKeyServiceClientFailure::Transport)?;
        if bytes.len() > {response_limit} {{
            return Err(ApiKeyServiceClientFailure::Transport);
        }}
        if !(200..300).contains(&status) {{
            let code = serde_json::from_slice::<serde_json::Value>(&bytes).ok()
                .and_then(|value| value.get("code")?.as_str().map(str::to_owned));
            return Err(match (status, code.as_deref()) {{
                (401, Some("authentication_rejected")) => ApiKeyServiceClientFailure::AuthenticationRejected,
                (404, Some("key_unavailable")) => ApiKeyServiceClientFailure::KeyUnavailable,
                (409, Some("stale_generation")) => ApiKeyServiceClientFailure::StaleGeneration,
                (409, Some("idempotency_conflict")) => ApiKeyServiceClientFailure::IdempotencyConflict,
                (503, Some("administration_unavailable")) => ApiKeyServiceClientFailure::AdministrationUnavailable,
                _ => ApiKeyServiceClientFailure::Transport,
            }});
        }}
        super::ApiKeyResponse::decode(&bytes).map_err(|_| ApiKeyServiceClientFailure::Transport)
    }}
}}
"#
    );
    std::fs::write(
        PathBuf::from(std::env::var("OUT_DIR")?).join("api_key_service_client.rs"),
        source,
    )?;
    Ok(())
}
