//! Generated from `positron.v1` service `CapabilityService/Negotiate` using `CapabilityRequest` and `CapabilityResponse`; do not edit.

/// Maximum accepted or emitted capability request body.
pub const MAX_PUBLIC_REQUEST_BYTES: usize = 64;

const GRPC_API_MAJOR_TAG: u8 = 8;
const GRPC_CAPABILITY_TAG: u8 = 16;

/// The one public API major version generated by this artifact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiVersion {
    /// Canonical Release 1 API package.
    V1,
}

impl ApiVersion {
    /// Returns the wire major version.
    #[must_use]
    pub const fn major(self) -> u32 {
        match self {
            Self::V1 => 1,
        }
    }
}

/// A checked nonzero API major requested by a caller or transport.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RequestedApiMajor(core::num::NonZeroU32);

impl RequestedApiMajor {
    const fn for_version(version: ApiVersion) -> Self {
        match version {
            ApiVersion::V1 => Self(core::num::NonZeroU32::MIN),
        }
    }

    /// Creates a checked requested major, rejecting the invalid zero value.
    pub const fn from_major(major: u32) -> Result<Self, ApiError> {
        match core::num::NonZeroU32::new(major) {
            Some(major) => Ok(Self(major)),
            None => Err(ApiError::unsupported_api_version()),
        }
    }

    /// Returns the requested wire major version.
    #[must_use]
    pub const fn major(self) -> u32 {
        self.0.get()
    }
}

/// Generated closed values from `Capability`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Capability {
    /// Generated from `CAPABILITY_UNSPECIFIED`.
    Unspecified = 0,
    /// Generated from `CAPABILITY_CANONICAL_PUBLIC_INTERFACE`.
    CanonicalPublicInterface = 1,
    /// Generated from `CAPABILITY_RELEASE_ONE_QUERY`.
    ReleaseOneQuery = 2,
    /// Generated from `CAPABILITY_METRICS`.
    Metrics = 3,
}

impl Capability {
    /// Returns the protobuf deprecation option for this value.
    #[must_use]
    pub const fn is_deprecated(self) -> bool {
        match self {
            Self::Unspecified => false,
            Self::CanonicalPublicInterface => false,
            Self::ReleaseOneQuery => false,
            Self::Metrics => false,
        }
    }
}

impl Capability {
    const fn wire_value(self) -> u32 {
        self as u32
    }

    fn from_wire(value: u32, source: ApiFailureSource) -> Result<Self, ApiError> {
        match value {
            0 => Ok(Self::CanonicalPublicInterface),
            1 => Ok(Self::CanonicalPublicInterface),
            2 => Ok(Self::ReleaseOneQuery),
            3 => Ok(Self::Metrics),
            _ => Err(ApiError::capability_unsupported(source)),
        }
    }
}

/// The stable SHA-256 identity of the canonical API definition.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SchemaDigest(&'static str);

impl SchemaDigest {
    /// Returns the digest embedded by deterministic generation.
    #[must_use]
    pub const fn canonical() -> Self {
        Self("dec4904c90127c22273f6f60287f054c3b6266731971d3418148517956d1e2f7")
    }

    /// Returns the lowercase hexadecimal digest value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        self.0
    }
}

/// Generated closed values from `CapabilityAvailability`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum CapabilityAvailability {
    /// Generated from `CAPABILITY_AVAILABILITY_UNSPECIFIED`.
    Unspecified = 0,
    /// Generated from `CAPABILITY_AVAILABILITY_IMPLEMENTED`.
    Implemented = 1,
    /// Generated from `CAPABILITY_AVAILABILITY_UNAVAILABLE`.
    Unavailable = 2,
    /// Generated from `CAPABILITY_AVAILABILITY_UNSUPPORTED`.
    Unsupported = 3,
    /// Generated from `CAPABILITY_AVAILABILITY_VERSION_INCOMPATIBLE`.
    VersionIncompatible = 4,
}

impl CapabilityAvailability {
    /// Returns the protobuf deprecation option for this value.
    #[must_use]
    pub const fn is_deprecated(self) -> bool {
        match self {
            Self::Unspecified => false,
            Self::Implemented => false,
            Self::Unavailable => false,
            Self::Unsupported => false,
            Self::VersionIncompatible => false,
        }
    }
}

/// Generated closed values from `DeprecationState`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum DeprecationState {
    /// Generated from `DEPRECATION_STATE_UNSPECIFIED`.
    Unspecified = 0,
    /// Generated from `DEPRECATION_STATE_CURRENT`.
    Current = 1,
    /// Generated from `DEPRECATION_STATE_DEPRECATED`.
    Deprecated = 2,
}

impl DeprecationState {
    /// Returns the protobuf deprecation option for this value.
    #[must_use]
    pub const fn is_deprecated(self) -> bool {
        match self {
            Self::Unspecified => false,
            Self::Current => false,
            Self::Deprecated => false,
        }
    }
}

/// Generated closed values from `RetryClass`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum RetryClass {
    /// Generated from `RETRY_CLASS_UNSPECIFIED`.
    Unspecified = 0,
    /// Generated from `RETRY_CLASS_NEVER`.
    Never = 1,
    /// Generated from `RETRY_CLASS_AFTER_BACKOFF`.
    AfterBackoff = 2,
    /// Generated from `RETRY_CLASS_AFTER_INPUT_CORRECTION`.
    AfterInputCorrection = 3,
}

impl RetryClass {
    /// Returns the protobuf deprecation option for this value.
    #[must_use]
    pub const fn is_deprecated(self) -> bool {
        match self {
            Self::Unspecified => false,
            Self::Never => false,
            Self::AfterBackoff => false,
            Self::AfterInputCorrection => false,
        }
    }
}

/// Generated closed values from `CompletionState`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum CompletionState {
    /// Generated from `COMPLETION_STATE_UNSPECIFIED`.
    Unspecified = 0,
    /// Generated from `COMPLETION_STATE_REJECTED`.
    Rejected = 1,
}

impl CompletionState {
    /// Returns the protobuf deprecation option for this value.
    #[must_use]
    pub const fn is_deprecated(self) -> bool {
        match self {
            Self::Unspecified => false,
            Self::Rejected => false,
        }
    }
}

/// Generated closed values from `PublicErrorCode`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ApiErrorCode {
    /// Generated from `PUBLIC_ERROR_CODE_UNSPECIFIED`.
    Unspecified = 0,
    /// Generated from `PUBLIC_ERROR_CODE_UNSUPPORTED_API_VERSION`.
    UnsupportedApiVersion = 1,
    /// Generated from `PUBLIC_ERROR_CODE_CAPABILITY_UNAVAILABLE`.
    CapabilityUnavailable = 2,
    /// Generated from `PUBLIC_ERROR_CODE_CAPABILITY_UNSUPPORTED`.
    CapabilityUnsupported = 3,
    /// Generated from `PUBLIC_ERROR_CODE_MALFORMED_REQUEST`.
    MalformedRequest = 4,
    /// Generated from `PUBLIC_ERROR_CODE_REQUEST_TOO_LARGE`.
    RequestTooLarge = 5,
    /// Generated from `PUBLIC_ERROR_CODE_UNKNOWN_FIELD`.
    UnknownField = 6,
}

impl ApiErrorCode {
    /// Returns the protobuf deprecation option for this value.
    #[must_use]
    pub const fn is_deprecated(self) -> bool {
        match self {
            Self::Unspecified => false,
            Self::UnsupportedApiVersion => false,
            Self::CapabilityUnavailable => false,
            Self::CapabilityUnsupported => false,
            Self::MalformedRequest => false,
            Self::RequestTooLarge => false,
            Self::UnknownField => false,
        }
    }
}

/// Generated closed values from `FailureSource`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ApiFailureSource {
    /// Generated from `FAILURE_SOURCE_UNSPECIFIED`.
    Unspecified = 0,
    /// Generated from `FAILURE_SOURCE_CAPABILITY_NEGOTIATION`.
    CapabilityNegotiation = 1,
    /// Generated from `FAILURE_SOURCE_GRPC_DECODE`.
    GrpcDecode = 2,
    /// Generated from `FAILURE_SOURCE_HTTP_DECODE`.
    HttpDecode = 3,
}

impl ApiFailureSource {
    /// Returns the protobuf deprecation option for this value.
    #[must_use]
    pub const fn is_deprecated(self) -> bool {
        match self {
            Self::Unspecified => false,
            Self::CapabilityNegotiation => false,
            Self::GrpcDecode => false,
            Self::HttpDecode => false,
        }
    }
}

/// Generated closed values from `SafeDetail`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum SafeDetail {
    /// Generated from `SAFE_DETAIL_UNSPECIFIED`.
    Unspecified = 0,
    /// Generated from `SAFE_DETAIL_API_MAJOR_UNSUPPORTED`.
    ApiMajorUnsupported = 1,
    /// Generated from `SAFE_DETAIL_CAPABILITY_NOT_AVAILABLE`.
    CapabilityNotAvailable = 2,
    /// Generated from `SAFE_DETAIL_CAPABILITY_NOT_SUPPORTED`.
    CapabilityNotSupported = 3,
    /// Generated from `SAFE_DETAIL_REQUEST_MALFORMED`.
    RequestMalformed = 4,
    /// Generated from `SAFE_DETAIL_REQUEST_LIMIT_EXCEEDED`.
    RequestLimitExceeded = 5,
    /// Generated from `SAFE_DETAIL_FIELD_NOT_RECOGNIZED`.
    FieldNotRecognized = 6,
}

impl SafeDetail {
    /// Returns the protobuf deprecation option for this value.
    #[must_use]
    pub const fn is_deprecated(self) -> bool {
        match self {
            Self::Unspecified => false,
            Self::ApiMajorUnsupported => false,
            Self::CapabilityNotAvailable => false,
            Self::CapabilityNotSupported => false,
            Self::RequestMalformed => false,
            Self::RequestLimitExceeded => false,
            Self::FieldNotRecognized => false,
        }
    }
}

/// A closed typed public failure with no caller-controlled diagnostic text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ApiError {
    code: ApiErrorCode,
    retry_class: RetryClass,
    completion_state: CompletionState,
    source: ApiFailureSource,
    safe_detail: SafeDetail,
}

impl ApiError {
    const fn unsupported_api_version() -> Self {
        Self {
            code: ApiErrorCode::UnsupportedApiVersion,
            retry_class: RetryClass::Never,
            completion_state: CompletionState::Rejected,
            source: ApiFailureSource::CapabilityNegotiation,
            safe_detail: SafeDetail::ApiMajorUnsupported,
        }
    }

    const fn capability_unavailable() -> Self {
        Self {
            code: ApiErrorCode::CapabilityUnavailable,
            retry_class: RetryClass::Never,
            completion_state: CompletionState::Rejected,
            source: ApiFailureSource::CapabilityNegotiation,
            safe_detail: SafeDetail::CapabilityNotAvailable,
        }
    }

    const fn capability_unsupported(source: ApiFailureSource) -> Self {
        Self {
            code: ApiErrorCode::CapabilityUnsupported,
            retry_class: RetryClass::Never,
            completion_state: CompletionState::Rejected,
            source,
            safe_detail: SafeDetail::CapabilityNotSupported,
        }
    }

    const fn malformed(source: ApiFailureSource) -> Self {
        Self {
            code: ApiErrorCode::MalformedRequest,
            retry_class: RetryClass::AfterInputCorrection,
            completion_state: CompletionState::Rejected,
            source,
            safe_detail: SafeDetail::RequestMalformed,
        }
    }

    const fn too_large(source: ApiFailureSource) -> Self {
        Self {
            code: ApiErrorCode::RequestTooLarge,
            retry_class: RetryClass::AfterInputCorrection,
            completion_state: CompletionState::Rejected,
            source,
            safe_detail: SafeDetail::RequestLimitExceeded,
        }
    }

    const fn unknown_field(source: ApiFailureSource) -> Self {
        Self {
            code: ApiErrorCode::UnknownField,
            retry_class: RetryClass::AfterInputCorrection,
            completion_state: CompletionState::Rejected,
            source,
            safe_detail: SafeDetail::FieldNotRecognized,
        }
    }

    /// Returns the stable public code.
    #[must_use]
    pub const fn code(self) -> ApiErrorCode {
        self.code
    }

    /// Returns the typed retry classification.
    #[must_use]
    pub const fn retry_class(self) -> RetryClass {
        self.retry_class
    }

    /// Returns whether the rejected request performed any work.
    #[must_use]
    pub const fn completion_state(self) -> CompletionState {
        self.completion_state
    }

    /// Returns the safe semantic failure location.
    #[must_use]
    pub const fn source(self) -> ApiFailureSource {
        self.source
    }

    /// Returns redaction-safe detail with no caller-controlled text.
    #[must_use]
    pub const fn safe_detail(self) -> SafeDetail {
        self.safe_detail
    }
}

/// Generated wire request for one API-major capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityRequest {
    api_major: Option<RequestedApiMajor>,
    capability: Capability,
}

impl CapabilityRequest {
    /// Creates a request for a generated API package.
    #[must_use]
    pub const fn for_version(version: ApiVersion) -> Self {
        Self {
            api_major: Some(RequestedApiMajor::for_version(version)),
            capability: Capability::CanonicalPublicInterface,
        }
    }

    /// Creates a request for one concrete generated capability.
    #[must_use]
    pub const fn for_capability(version: ApiVersion, capability: Capability) -> Self {
        Self {
            api_major: Some(RequestedApiMajor::for_version(version)),
            capability,
        }
    }

    /// Creates a request for a checked caller-requested API major.
    #[must_use]
    pub const fn for_requested_major(
        requested_major: RequestedApiMajor,
        capability: Capability,
    ) -> Self {
        Self {
            api_major: Some(requested_major),
            capability,
        }
    }

    /// Creates a request carrying an unknown wire major for checked refusal.
    #[must_use]
    pub const fn unknown(api_major: u32, capability: Capability) -> Self {
        let api_major = match RequestedApiMajor::from_major(api_major) {
            Ok(api_major) => Some(api_major),
            Err(_) => None,
        };
        Self {
            api_major,
            capability,
        }
    }

    const fn wire_major(self) -> u32 {
        match self.api_major {
            Some(api_major) => api_major.major(),
            None => 0,
        }
    }
}

/// Generated typed response for capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityResponse {
    availability: CapabilityAvailability,
    api_major: ApiVersion,
    schema_digest: SchemaDigest,
    refusal: Option<ApiError>,
    deprecation: DeprecationState,
    capability: Capability,
}

impl CapabilityResponse {
    /// Returns the closed capability availability truth.
    #[must_use]
    pub const fn availability(self) -> CapabilityAvailability {
        self.availability
    }

    /// Returns the negotiated public API package.
    #[must_use]
    pub const fn api_major(self) -> ApiVersion {
        self.api_major
    }

    /// Returns the generated source identity.
    #[must_use]
    pub const fn schema_digest(self) -> SchemaDigest {
        self.schema_digest
    }

    /// Returns a stable refusal when negotiation did not succeed.
    #[must_use]
    pub const fn refusal(self) -> Option<ApiError> {
        self.refusal
    }

    /// Returns the explicit compatibility deprecation state.
    #[must_use]
    pub const fn deprecation(self) -> DeprecationState {
        self.deprecation
    }

    /// Returns the concrete capability described by this statement.
    #[must_use]
    pub const fn capability(self) -> Capability {
        self.capability
    }
}

/// The generated public transport mappings.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Transport {
    /// Protobuf body on the generated gRPC method path.
    GrpcProtobuf,
    /// JSON body on the generated HTTP route.
    HttpJson,
}

impl Transport {
    const fn source(self) -> ApiFailureSource {
        match self {
            Self::GrpcProtobuf => ApiFailureSource::GrpcDecode,
            Self::HttpJson => ApiFailureSource::HttpDecode,
        }
    }
}

/// A bounded generated client request with no network or runtime orchestration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EncodedRequest {
    body: Vec<u8>,
    path: &'static str,
}

impl EncodedRequest {
    fn empty(path: &'static str) -> Self {
        Self {
            body: Vec::with_capacity(MAX_PUBLIC_REQUEST_BYTES),
            path,
        }
    }

    fn push(&mut self, byte: u8) {
        self.body.push(byte);
    }

    fn extend(&mut self, bytes: &[u8]) {
        self.body.extend_from_slice(bytes);
    }

    /// Returns the generated HTTP method.
    #[must_use]
    pub const fn method(&self) -> &'static str {
        "POST"
    }

    /// Returns the generated gRPC or HTTP path.
    #[must_use]
    pub const fn path(&self) -> &'static str {
        self.path
    }

    /// Returns the initialized bounded request body.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        &self.body
    }
}

/// Published allocation and copy bounds for generated client encoding.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ClientEncodingBounds;

impl ClientEncodingBounds {
    /// Maximum emitted body bytes for either generated transport.
    #[must_use]
    pub const fn maximum_body_bytes(self) -> usize {
        MAX_PUBLIC_REQUEST_BYTES
    }

    /// One 64-byte body buffer is reserved before encoding.
    #[must_use]
    pub const fn maximum_heap_buffers(self) -> usize {
        1
    }

    /// Encoding creates no intermediate heap-backed body.
    #[must_use]
    pub const fn maximum_intermediate_heap_bytes(self) -> usize {
        0
    }

    /// Encoding never copies a completed body into another buffer.
    #[must_use]
    pub const fn maximum_full_body_copies(self) -> usize {
        0
    }
}

/// Generated client encoder contract with no I/O or ambient authority.
pub struct CapabilityClient;

impl CapabilityClient {
    /// Returns the externally reachable client encoding resource contract.
    #[must_use]
    pub const fn encoding_bounds() -> ClientEncodingBounds {
        ClientEncodingBounds
    }

    /// Encodes one typed request into its bounded generated transport body.
    ///
    /// The generated two-`u32` request model cannot exceed the published body
    /// bound, so typed client encoding has no input-dependent failure.
    #[must_use]
    pub fn encode(request: CapabilityRequest, transport: Transport) -> EncodedRequest {
        match transport {
            Transport::GrpcProtobuf => encode_grpc(request),
            Transport::HttpJson => encode_http(request),
        }
    }
}

/// Generated in-memory service boundary for the canonical capability contract.
pub struct CapabilityService;

impl CapabilityService {
    /// Negotiates one bounded, versioned public API request without ambient state.
    #[must_use]
    pub const fn negotiate(request: CapabilityRequest) -> CapabilityResponse {
        let version_refusal = match request.api_major {
            Some(requested_major) if requested_major.major() == ApiVersion::V1.major() => None,
            Some(_) | None => Some(ApiError::unsupported_api_version()),
        };
        if let Some(refusal) = version_refusal {
            return CapabilityResponse {
                availability: CapabilityAvailability::VersionIncompatible,
                api_major: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: Some(refusal),
                deprecation: DeprecationState::Current,
                capability: request.capability,
            };
        }
        match request.capability {
            Capability::Unspecified | Capability::CanonicalPublicInterface => CapabilityResponse {
                availability: CapabilityAvailability::Implemented,
                api_major: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: None,
                deprecation: DeprecationState::Current,
                capability: Capability::CanonicalPublicInterface,
            },
            Capability::ReleaseOneQuery => CapabilityResponse {
                availability: CapabilityAvailability::Unavailable,
                api_major: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: Some(ApiError::capability_unavailable()),
                deprecation: DeprecationState::Current,
                capability: request.capability,
            },
            Capability::Metrics => CapabilityResponse {
                availability: CapabilityAvailability::Unsupported,
                api_major: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: Some(ApiError::capability_unsupported(
                    ApiFailureSource::CapabilityNegotiation,
                )),
                deprecation: DeprecationState::Current,
                capability: request.capability,
            },
        }
    }

    /// Decodes one bounded transport body exactly once and maps its typed outcome.
    pub fn decode_and_negotiate(
        transport: Transport,
        body: &[u8],
    ) -> Result<CapabilityResponse, ApiError> {
        if body.len() > MAX_PUBLIC_REQUEST_BYTES {
            return Err(ApiError::too_large(transport.source()));
        }
        let request = match transport {
            Transport::GrpcProtobuf => decode_grpc(body)?,
            Transport::HttpJson => decode_http(body)?,
        };
        Ok(Self::negotiate(request))
    }
}

fn encode_grpc(request: CapabilityRequest) -> EncodedRequest {
    let mut encoded = EncodedRequest::empty("/positron.v1.CapabilityService/Negotiate");
    encoded.push(GRPC_API_MAJOR_TAG);
    encode_varint(request.wire_major(), &mut encoded);
    encoded.push(GRPC_CAPABILITY_TAG);
    encode_varint(request.capability.wire_value(), &mut encoded);
    encoded
}

fn encode_http(request: CapabilityRequest) -> EncodedRequest {
    let mut encoded = EncodedRequest::empty("/v1/capabilities:negotiate");
    encoded.extend(b"{\"api_major\":");
    encode_json_u32(request.wire_major(), &mut encoded);
    encoded.extend(b",\"capability\":");
    encode_json_u32(request.capability.wire_value(), &mut encoded);
    encoded.extend(b"}");
    encoded
}

fn encode_json_u32(mut value: u32, encoded: &mut EncodedRequest) {
    if value == 0 {
        encoded.push(b'0');
        return;
    }
    let mut digits = [0_u8; 10];
    let digit_count = value.ilog10() as usize + 1;
    for slot in digits.iter_mut().rev().take(digit_count) {
        // The modulo bounds this narrowing conversion to `0..=9`.
        let digit = (value % 10) as u8;
        *slot = b'0' + digit;
        value /= 10;
    }
    let first_digit = digits.len() - digit_count;
    for digit in digits.into_iter().skip(first_digit) {
        encoded.push(digit);
    }
}

fn encode_varint(mut value: u32, encoded: &mut EncodedRequest) {
    // A `u32` has at most five seven-bit groups. Only the first four can
    // carry a continuation bit; the fifth group is always terminal.
    for _ in 0..4 {
        // The mask bounds this narrowing conversion to seven bits.
        let byte = (value & 0x7f) as u8;
        value >>= 7;
        if value == 0 {
            encoded.push(byte);
            return;
        }
        encoded.push(byte.saturating_add(0x80));
    }
    // Four seven-bit shifts leave at most the high four bits of the `u32`.
    encoded.push(value as u8);
}

fn decode_grpc(body: &[u8]) -> Result<CapabilityRequest, ApiError> {
    let source = ApiFailureSource::GrpcDecode;
    let mut cursor = 0;
    let mut api_major = None;
    let mut capability = None;
    while let Some(tag) = body.get(cursor).copied() {
        cursor += 1;
        let (value, next) = decode_varint(body, cursor, source)?;
        cursor = next;
        match tag {
            GRPC_API_MAJOR_TAG if api_major.is_none() => api_major = Some(value),
            GRPC_CAPABILITY_TAG if capability.is_none() => {
                capability = Some(Capability::from_wire(value, source)?);
            },
            GRPC_API_MAJOR_TAG | GRPC_CAPABILITY_TAG => return Err(ApiError::malformed(source)),
            _ => return Err(ApiError::unknown_field(source)),
        }
    }
    let Some(api_major) = api_major else {
        return Err(ApiError::malformed(source));
    };
    Ok(CapabilityRequest::unknown(
        api_major,
        match capability {
            Some(capability) => capability,
            None => Capability::CanonicalPublicInterface,
        },
    ))
}

fn decode_varint(
    body: &[u8],
    mut cursor: usize,
    source: ApiFailureSource,
) -> Result<(u32, usize), ApiError> {
    let mut value = 0_u32;
    for shift in [0, 7, 14, 21, 28] {
        let Some(byte) = body.get(cursor).copied() else {
            return Err(ApiError::malformed(source));
        };
        cursor += 1;
        if shift == 28 && byte & 0x7f > 0x0f {
            return Err(ApiError::malformed(source));
        }
        value |= u32::from(byte & 0x7f) << shift;
        if byte & 0x80 == 0 {
            return Ok((value, cursor));
        }
    }
    Err(ApiError::malformed(source))
}

fn trim_json_whitespace(value: &str) -> &str {
    value.trim_matches(&[' ', '\t', '\r', '\n'][..])
}

fn decode_http(body: &[u8]) -> Result<CapabilityRequest, ApiError> {
    let source = ApiFailureSource::HttpDecode;
    let text =
        trim_json_whitespace(core::str::from_utf8(body).map_err(|_| ApiError::malformed(source))?);
    let Some(object) = text
        .strip_prefix('{')
        .and_then(|value| value.strip_suffix('}'))
    else {
        return Err(ApiError::malformed(source));
    };
    let mut api_major = None;
    let mut capability = None;
    for member in object.split(',') {
        let Some((key, value)) = member.split_once(':') else {
            return Err(ApiError::malformed(source));
        };
        let key = trim_json_whitespace(key);
        match key {
            "\"api_major\"" if api_major.is_none() => {
                api_major = Some(parse_json_u32(value, source)?);
            },
            "\"capability\"" if capability.is_none() => {
                capability = Some(Capability::from_wire(
                    parse_json_u32(value, source)?,
                    source,
                )?);
            },
            "\"api_major\"" | "\"capability\"" => {
                return Err(ApiError::malformed(source));
            },
            _ if key.starts_with('"') && key.ends_with('"') => {
                return Err(ApiError::unknown_field(source));
            },
            _ => return Err(ApiError::malformed(source)),
        }
    }
    let Some(api_major) = api_major else {
        return Err(ApiError::malformed(source));
    };
    Ok(CapabilityRequest::unknown(
        api_major,
        match capability {
            Some(capability) => capability,
            None => Capability::CanonicalPublicInterface,
        },
    ))
}

fn parse_json_u32(value: &str, source: ApiFailureSource) -> Result<u32, ApiError> {
    let value = trim_json_whitespace(value);
    let bytes = value.as_bytes();
    let canonical = match bytes {
        [b'0'] => true,
        [first, rest @ ..] => (b'1'..=b'9').contains(first) && rest.iter().all(u8::is_ascii_digit),
        [] => false,
    };
    if !canonical {
        return Err(ApiError::malformed(source));
    }
    value
        .parse::<u32>()
        .map_err(|_| ApiError::malformed(source))
}
