//! Generated from `positron.v1` service `CapabilityService/Negotiate` using `CapabilityRequest` and `CapabilityResponse`; do not edit.

/// Maximum accepted or emitted capability request body.
pub const MAX_PUBLIC_REQUEST_BYTES: usize = 64;

const GRPC_API_MAJOR_TAG: u8 = 8;
const GRPC_CAPABILITY_TAG: u8 = 16;

/// The one public API major version generated by this artifact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiVersion {
    /// Canonical Release 1 API package.
    V1,
}

impl ApiVersion {
    /// Returns the wire major version.
    #[must_use]
    pub const fn major(self) -> u32 {
        match self {
            Self::V1 => 1,
        }
    }
}

/// The concrete behaviors described by the generated capability statement.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Capability {
    /// This canonical generated public interface.
    CanonicalPublicInterface,
    /// Release 1 query behavior, which is known but not yet available.
    ReleaseOneQuery,
    /// Metrics, which is explicitly outside Release 1 product scope.
    Metrics,
}

impl Capability {
    const fn wire_value(self) -> u32 {
        match self {
            Self::CanonicalPublicInterface => 1,
            Self::ReleaseOneQuery => 2,
            Self::Metrics => 3,
        }
    }

    fn from_wire(value: u32, source: ApiFailureSource) -> Result<Self, ApiError> {
        match value {
            0 | 1 => Ok(Self::CanonicalPublicInterface),
            2 => Ok(Self::ReleaseOneQuery),
            3 => Ok(Self::Metrics),
            _ => Err(ApiError::capability_unsupported(source)),
        }
    }
}

/// The stable SHA-256 identity of the canonical API definition.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SchemaDigest(&'static str);

impl SchemaDigest {
    /// Returns the digest embedded by deterministic generation.
    #[must_use]
    pub const fn canonical() -> Self {
        Self("dec4904c90127c22273f6f60287f054c3b6266731971d3418148517956d1e2f7")
    }

    /// Returns the lowercase hexadecimal digest value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        self.0
    }
}

/// The closed availability truth returned by capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityAvailability {
    /// The requested API package is implemented by this server.
    Implemented,
    /// A known capability is not available in this server state.
    Unavailable,
    /// The server does not support the requested capability.
    Unsupported,
    /// The request requires an API package this server cannot interpret.
    VersionIncompatible,
}

/// The explicit public deprecation truth for a negotiated behavior.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DeprecationState {
    /// The behavior is current and has no deprecation notice.
    Current,
    /// The behavior remains accepted but has a published replacement.
    Deprecated,
}

/// The closed retry classification attached to a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RetryClass {
    /// Retrying the same request cannot change the outcome.
    Never,
    /// The caller may retry after an owner-directed bounded backoff.
    AfterBackoff,
    /// The caller must first correct its input.
    AfterInputCorrection,
}

/// The closed completion truth attached to a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CompletionState {
    /// The request was rejected before work began.
    Rejected,
}

/// Stable public error codes for the generated capability foundation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiErrorCode {
    /// The requested API major has no compatible handler.
    UnsupportedApiVersion,
    /// The capability is known but unavailable in this server state.
    CapabilityUnavailable,
    /// The capability is outside this server's supported product scope.
    CapabilityUnsupported,
    /// The transport body cannot be decoded.
    MalformedRequest,
    /// The transport body exceeds its published bound.
    RequestTooLarge,
    /// The transport body contains a field this interface does not accept.
    UnknownField,
}

/// A non-secret semantic location for a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiFailureSource {
    /// API package negotiation rejected the request.
    CapabilityNegotiation,
    /// The generated gRPC protobuf boundary rejected the body.
    GrpcDecode,
    /// The generated HTTP JSON boundary rejected the body.
    HttpDecode,
}

/// Closed, redaction-safe detail for every public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SafeDetail {
    /// The requested API major is not supported.
    ApiMajorUnsupported,
    /// The known capability is not available.
    CapabilityNotAvailable,
    /// The requested capability is not supported.
    CapabilityNotSupported,
    /// The request body is malformed.
    RequestMalformed,
    /// The request body exceeds the declared limit.
    RequestLimitExceeded,
    /// A request field is not recognized.
    FieldNotRecognized,
}

/// A closed typed public failure with no caller-controlled diagnostic text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ApiError {
    code: ApiErrorCode,
    retry_class: RetryClass,
    completion_state: CompletionState,
    source: ApiFailureSource,
    safe_detail: SafeDetail,
}

impl ApiError {
    const fn unsupported_api_version() -> Self {
        Self {
            code: ApiErrorCode::UnsupportedApiVersion,
            retry_class: RetryClass::Never,
            completion_state: CompletionState::Rejected,
            source: ApiFailureSource::CapabilityNegotiation,
            safe_detail: SafeDetail::ApiMajorUnsupported,
        }
    }

    const fn capability_unavailable() -> Self {
        Self {
            code: ApiErrorCode::CapabilityUnavailable,
            retry_class: RetryClass::Never,
            completion_state: CompletionState::Rejected,
            source: ApiFailureSource::CapabilityNegotiation,
            safe_detail: SafeDetail::CapabilityNotAvailable,
        }
    }

    const fn capability_unsupported(source: ApiFailureSource) -> Self {
        Self {
            code: ApiErrorCode::CapabilityUnsupported,
            retry_class: RetryClass::Never,
            completion_state: CompletionState::Rejected,
            source,
            safe_detail: SafeDetail::CapabilityNotSupported,
        }
    }

    const fn malformed(source: ApiFailureSource) -> Self {
        Self {
            code: ApiErrorCode::MalformedRequest,
            retry_class: RetryClass::AfterInputCorrection,
            completion_state: CompletionState::Rejected,
            source,
            safe_detail: SafeDetail::RequestMalformed,
        }
    }

    const fn too_large(source: ApiFailureSource) -> Self {
        Self {
            code: ApiErrorCode::RequestTooLarge,
            retry_class: RetryClass::AfterInputCorrection,
            completion_state: CompletionState::Rejected,
            source,
            safe_detail: SafeDetail::RequestLimitExceeded,
        }
    }

    const fn unknown_field(source: ApiFailureSource) -> Self {
        Self {
            code: ApiErrorCode::UnknownField,
            retry_class: RetryClass::AfterInputCorrection,
            completion_state: CompletionState::Rejected,
            source,
            safe_detail: SafeDetail::FieldNotRecognized,
        }
    }

    /// Returns the stable public code.
    #[must_use]
    pub const fn code(self) -> ApiErrorCode {
        self.code
    }

    /// Returns the typed retry classification.
    #[must_use]
    pub const fn retry_class(self) -> RetryClass {
        self.retry_class
    }

    /// Returns whether the rejected request performed any work.
    #[must_use]
    pub const fn completion_state(self) -> CompletionState {
        self.completion_state
    }

    /// Returns the safe semantic failure location.
    #[must_use]
    pub const fn source(self) -> ApiFailureSource {
        self.source
    }

    /// Returns redaction-safe detail with no caller-controlled text.
    #[must_use]
    pub const fn safe_detail(self) -> SafeDetail {
        self.safe_detail
    }
}

/// Generated wire request for one API-major capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityRequest {
    api_major: u32,
    capability: Capability,
}

impl CapabilityRequest {
    /// Creates a request for a generated API package.
    #[must_use]
    pub const fn for_version(version: ApiVersion) -> Self {
        Self {
            api_major: version.major(),
            capability: Capability::CanonicalPublicInterface,
        }
    }

    /// Creates a request for one concrete generated capability.
    #[must_use]
    pub const fn for_capability(version: ApiVersion, capability: Capability) -> Self {
        Self {
            api_major: version.major(),
            capability,
        }
    }

    /// Creates a request carrying an unknown wire major for checked refusal.
    #[must_use]
    pub const fn unknown(api_major: u32, capability: Capability) -> Self {
        Self {
            api_major,
            capability,
        }
    }
}

/// Generated typed response for capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityResponse {
    availability: CapabilityAvailability,
    api_version: ApiVersion,
    schema_digest: SchemaDigest,
    refusal: Option<ApiError>,
    deprecation: DeprecationState,
    capability: Capability,
}

impl CapabilityResponse {
    /// Returns the closed capability availability truth.
    #[must_use]
    pub const fn availability(self) -> CapabilityAvailability {
        self.availability
    }

    /// Returns the negotiated public API package.
    #[must_use]
    pub const fn api_version(self) -> ApiVersion {
        self.api_version
    }

    /// Returns the generated source identity.
    #[must_use]
    pub const fn schema_digest(self) -> SchemaDigest {
        self.schema_digest
    }

    /// Returns a stable refusal when negotiation did not succeed.
    #[must_use]
    pub const fn refusal(self) -> Option<ApiError> {
        self.refusal
    }

    /// Returns the explicit compatibility deprecation state.
    #[must_use]
    pub const fn deprecation(self) -> DeprecationState {
        self.deprecation
    }

    /// Returns the concrete capability described by this statement.
    #[must_use]
    pub const fn capability(self) -> Capability {
        self.capability
    }
}

/// The generated public transport mappings.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Transport {
    /// Protobuf body on the generated gRPC method path.
    GrpcProtobuf,
    /// JSON body on the generated HTTP route.
    HttpJson,
}

impl Transport {
    const fn source(self) -> ApiFailureSource {
        match self {
            Self::GrpcProtobuf => ApiFailureSource::GrpcDecode,
            Self::HttpJson => ApiFailureSource::HttpDecode,
        }
    }
}

/// A bounded generated client request with no network or runtime orchestration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EncodedRequest {
    body: Vec<u8>,
    path: &'static str,
}

impl EncodedRequest {
    fn empty(path: &'static str) -> Self {
        Self {
            body: Vec::with_capacity(MAX_PUBLIC_REQUEST_BYTES),
            path,
        }
    }

    fn push(&mut self, byte: u8, source: ApiFailureSource) -> Result<(), ApiError> {
        if self.body.len() >= MAX_PUBLIC_REQUEST_BYTES {
            return Err(ApiError::too_large(source));
        }
        self.body.push(byte);
        Ok(())
    }

    fn extend(&mut self, bytes: &[u8], source: ApiFailureSource) -> Result<(), ApiError> {
        let Some(end) = self.body.len().checked_add(bytes.len()) else {
            return Err(ApiError::too_large(source));
        };
        if end > MAX_PUBLIC_REQUEST_BYTES {
            return Err(ApiError::too_large(source));
        }
        self.body.extend_from_slice(bytes);
        Ok(())
    }

    /// Returns the generated HTTP method.
    #[must_use]
    pub const fn method(&self) -> &'static str {
        "POST"
    }

    /// Returns the generated gRPC or HTTP path.
    #[must_use]
    pub const fn path(&self) -> &'static str {
        self.path
    }

    /// Returns the initialized bounded request body.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        &self.body
    }
}

/// Generated client encoder contract with no I/O or ambient authority.
pub struct CapabilityClient;

impl CapabilityClient {
    /// Encodes one typed request into its bounded generated transport body.
    pub fn encode(
        request: CapabilityRequest,
        transport: Transport,
    ) -> Result<EncodedRequest, ApiError> {
        match transport {
            Transport::GrpcProtobuf => encode_grpc(request),
            Transport::HttpJson => encode_http(request),
        }
    }
}

/// Generated in-memory service boundary for the canonical capability contract.
pub struct CapabilityService;

impl CapabilityService {
    /// Negotiates one bounded, versioned public API request without ambient state.
    #[must_use]
    pub const fn negotiate(request: CapabilityRequest) -> CapabilityResponse {
        if request.api_major != ApiVersion::V1.major() {
            return CapabilityResponse {
                availability: CapabilityAvailability::VersionIncompatible,
                api_version: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: Some(ApiError::unsupported_api_version()),
                deprecation: DeprecationState::Current,
                capability: request.capability,
            };
        }
        match request.capability {
            Capability::CanonicalPublicInterface => CapabilityResponse {
                availability: CapabilityAvailability::Implemented,
                api_version: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: None,
                deprecation: DeprecationState::Current,
                capability: request.capability,
            },
            Capability::ReleaseOneQuery => CapabilityResponse {
                availability: CapabilityAvailability::Unavailable,
                api_version: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: Some(ApiError::capability_unavailable()),
                deprecation: DeprecationState::Current,
                capability: request.capability,
            },
            Capability::Metrics => CapabilityResponse {
                availability: CapabilityAvailability::Unsupported,
                api_version: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: Some(ApiError::capability_unsupported(
                    ApiFailureSource::CapabilityNegotiation,
                )),
                deprecation: DeprecationState::Current,
                capability: request.capability,
            },
        }
    }

    /// Decodes one bounded transport body exactly once and maps its typed outcome.
    pub fn decode_and_negotiate(
        transport: Transport,
        body: &[u8],
    ) -> Result<CapabilityResponse, ApiError> {
        if body.len() > MAX_PUBLIC_REQUEST_BYTES {
            return Err(ApiError::too_large(transport.source()));
        }
        let request = match transport {
            Transport::GrpcProtobuf => decode_grpc(body)?,
            Transport::HttpJson => decode_http(body)?,
        };
        Ok(Self::negotiate(request))
    }
}

fn encode_grpc(request: CapabilityRequest) -> Result<EncodedRequest, ApiError> {
    let source = ApiFailureSource::GrpcDecode;
    let mut encoded = EncodedRequest::empty("/positron.v1.CapabilityService/Negotiate");
    encoded.push(GRPC_API_MAJOR_TAG, source)?;
    encode_varint(request.api_major, &mut encoded, source)?;
    encoded.push(GRPC_CAPABILITY_TAG, source)?;
    encode_varint(request.capability.wire_value(), &mut encoded, source)?;
    Ok(encoded)
}

fn encode_http(request: CapabilityRequest) -> Result<EncodedRequest, ApiError> {
    let source = ApiFailureSource::HttpDecode;
    let mut encoded = EncodedRequest::empty("/v1/capabilities:negotiate");
    let body = format!(
        r#"{{"api_major":{},"capability":{}}}"#,
        request.api_major,
        request.capability.wire_value()
    );
    encoded.extend(body.as_bytes(), source)?;
    Ok(encoded)
}

fn encode_varint(
    mut value: u32,
    encoded: &mut EncodedRequest,
    source: ApiFailureSource,
) -> Result<(), ApiError> {
    loop {
        let byte = u8::try_from(value & 0x7f).map_err(|_| ApiError::malformed(source))?;
        value >>= 7;
        if value == 0 {
            encoded.push(byte, source)?;
            return Ok(());
        }
        encoded.push(byte | 0x80, source)?;
    }
}

fn decode_grpc(body: &[u8]) -> Result<CapabilityRequest, ApiError> {
    let source = ApiFailureSource::GrpcDecode;
    let mut cursor = 0;
    let mut api_major = None;
    let mut capability = None;
    while cursor < body.len() {
        let Some(tag) = body.get(cursor).copied() else {
            return Err(ApiError::malformed(source));
        };
        cursor += 1;
        let (value, next) = decode_varint(body, cursor, source)?;
        cursor = next;
        match tag {
            GRPC_API_MAJOR_TAG if api_major.is_none() => api_major = Some(value),
            GRPC_CAPABILITY_TAG if capability.is_none() => {
                capability = Some(Capability::from_wire(value, source)?);
            },
            GRPC_API_MAJOR_TAG | GRPC_CAPABILITY_TAG => return Err(ApiError::malformed(source)),
            _ => return Err(ApiError::unknown_field(source)),
        }
    }
    let Some(api_major) = api_major else {
        return Err(ApiError::malformed(source));
    };
    Ok(CapabilityRequest {
        api_major,
        capability: match capability {
            Some(capability) => capability,
            None => Capability::CanonicalPublicInterface,
        },
    })
}

fn decode_varint(
    body: &[u8],
    mut cursor: usize,
    source: ApiFailureSource,
) -> Result<(u32, usize), ApiError> {
    let mut value = 0_u32;
    for shift in [0, 7, 14, 21, 28] {
        let Some(byte) = body.get(cursor).copied() else {
            return Err(ApiError::malformed(source));
        };
        cursor += 1;
        value |= u32::from(byte & 0x7f) << shift;
        if byte & 0x80 == 0 {
            return Ok((value, cursor));
        }
    }
    Err(ApiError::malformed(source))
}

fn decode_http(body: &[u8]) -> Result<CapabilityRequest, ApiError> {
    let source = ApiFailureSource::HttpDecode;
    let text = core::str::from_utf8(body)
        .map_err(|_| ApiError::malformed(source))?
        .trim();
    let Some(object) = text
        .strip_prefix('{')
        .and_then(|value| value.strip_suffix('}'))
    else {
        return Err(ApiError::malformed(source));
    };
    let mut api_major = None;
    let mut capability = None;
    for member in object.split(',') {
        let Some((key, value)) = member.split_once(':') else {
            return Err(ApiError::malformed(source));
        };
        match key.trim() {
            "\"api_major\"" if api_major.is_none() => {
                api_major = Some(parse_json_u32(value, source)?);
            },
            "\"capability\"" if capability.is_none() => {
                capability = Some(Capability::from_wire(
                    parse_json_u32(value, source)?,
                    source,
                )?);
            },
            "\"api_major\"" | "\"capability\"" => {
                return Err(ApiError::malformed(source));
            },
            _ => return Err(ApiError::unknown_field(source)),
        }
    }
    let Some(api_major) = api_major else {
        return Err(ApiError::malformed(source));
    };
    Ok(CapabilityRequest {
        api_major,
        capability: match capability {
            Some(capability) => capability,
            None => Capability::CanonicalPublicInterface,
        },
    })
}

fn parse_json_u32(value: &str, source: ApiFailureSource) -> Result<u32, ApiError> {
    value
        .trim()
        .parse::<u32>()
        .map_err(|_| ApiError::malformed(source))
}
