//! Generated from `api/positron/v1/positron.proto`; do not edit.

/// The one public API major version generated by this artifact.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiVersion {
    /// Canonical Release 1 API package.
    V1,
}

impl ApiVersion {
    /// Returns the wire major version.
    #[must_use]
    pub const fn major(self) -> u32 {
        match self {
            Self::V1 => 1,
        }
    }
}

/// The stable SHA-256 identity of the canonical API definition.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SchemaDigest(&'static str);

impl SchemaDigest {
    /// Returns the digest embedded by deterministic generation.
    #[must_use]
    pub const fn canonical() -> Self {
        Self("65bbd45e3342bbd8b7da71e478be76f1f3057dbaabce6aa31cae76c47d5cba11")
    }

    /// Returns the lowercase hexadecimal digest value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        self.0
    }
}

/// The closed availability truth returned by capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityAvailability {
    /// The requested API package is implemented by this server.
    Implemented,
    /// A known capability is not available in this server state.
    Unavailable,
    /// The server does not support the requested capability.
    Unsupported,
    /// The request requires an API package this server cannot interpret.
    VersionIncompatible,
}

/// The closed retry classification attached to a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RetryClass {
    /// Retrying the same request cannot change the outcome.
    Never,
    /// The caller may retry after an owner-directed bounded backoff.
    AfterBackoff,
    /// The caller must first correct its input.
    AfterInputCorrection,
}

/// The closed completion truth attached to a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CompletionState {
    /// The request was rejected before work began.
    Rejected,
}

/// Stable public error codes for the generated capability foundation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiErrorCode {
    /// The requested API major has no compatible handler.
    UnsupportedApiVersion,
}

/// A non-secret semantic location for a public failure.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiFailureSource {
    /// API package negotiation rejected the request.
    CapabilityNegotiation,
}

/// A closed typed public failure with no caller-controlled diagnostic text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ApiError {
    code: ApiErrorCode,
    retry_class: RetryClass,
    completion_state: CompletionState,
    source: ApiFailureSource,
}

impl ApiError {
    const fn unsupported_api_version() -> Self {
        Self {
            code: ApiErrorCode::UnsupportedApiVersion,
            retry_class: RetryClass::Never,
            completion_state: CompletionState::Rejected,
            source: ApiFailureSource::CapabilityNegotiation,
        }
    }

    /// Returns the stable public code.
    #[must_use]
    pub const fn code(self) -> ApiErrorCode {
        self.code
    }

    /// Returns the typed retry classification.
    #[must_use]
    pub const fn retry_class(self) -> RetryClass {
        self.retry_class
    }

    /// Returns whether the rejected request performed any work.
    #[must_use]
    pub const fn completion_state(self) -> CompletionState {
        self.completion_state
    }

    /// Returns the safe semantic failure location.
    #[must_use]
    pub const fn source(self) -> ApiFailureSource {
        self.source
    }
}

/// Generated wire request for one API-major capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityRequest {
    api_major: u32,
}

impl CapabilityRequest {
    /// Creates a request for a generated API package.
    #[must_use]
    pub const fn for_version(version: ApiVersion) -> Self {
        Self {
            api_major: version.major(),
        }
    }

    /// Creates a request carrying an unknown wire major for checked refusal.
    #[must_use]
    pub const fn unknown(api_major: u32) -> Self {
        Self { api_major }
    }
}

/// Generated typed response for capability negotiation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CapabilityResponse {
    availability: CapabilityAvailability,
    api_version: ApiVersion,
    schema_digest: SchemaDigest,
    refusal: Option<ApiError>,
}

impl CapabilityResponse {
    /// Returns the closed capability availability truth.
    #[must_use]
    pub const fn availability(self) -> CapabilityAvailability {
        self.availability
    }

    /// Returns the negotiated public API package.
    #[must_use]
    pub const fn api_version(self) -> ApiVersion {
        self.api_version
    }

    /// Returns the generated source identity.
    #[must_use]
    pub const fn schema_digest(self) -> SchemaDigest {
        self.schema_digest
    }

    /// Returns a stable refusal when negotiation did not succeed.
    #[must_use]
    pub const fn refusal(self) -> Option<ApiError> {
        self.refusal
    }
}

/// Generated in-memory service boundary for the canonical capability contract.
pub struct CapabilityService;

impl CapabilityService {
    /// Negotiates one bounded, versioned public API request without ambient state.
    #[must_use]
    pub const fn negotiate(request: CapabilityRequest) -> CapabilityResponse {
        if request.api_major == ApiVersion::V1.major() {
            CapabilityResponse {
                availability: CapabilityAvailability::Implemented,
                api_version: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: None,
            }
        } else {
            CapabilityResponse {
                availability: CapabilityAvailability::VersionIncompatible,
                api_version: ApiVersion::V1,
                schema_digest: SchemaDigest::canonical(),
                refusal: Some(ApiError::unsupported_api_version()),
            }
        }
    }
}
