use std::error::Error;

use super::super::validation::ValidatedOperations;
use super::write_generated;

pub(super) fn generate_maintenance_client(
    operations: &ValidatedOperations,
) -> Result<(), Box<dyn Error>> {
    let operation = operations.operation("positron.v1.MaintenanceService/Status")?;
    let path = operation.path();
    let request_limit = operation.request_limit();
    let response_limit = operation.response_limit();
    let source = format!(
        r#"// Generated by positron-api/build.rs from MaintenanceService in the canonical protobuf descriptor and HTTP mapping. Do not edit.
use std::io::Read;
use std::time::Duration;
#[derive(Clone, Copy, Debug, Eq, PartialEq)] pub enum MaintenanceServiceClientFailure {{ InvalidRequest, AuthenticationRejected, AdministrationUnavailable, Transport }}
impl std::fmt::Display for MaintenanceServiceClientFailure {{ fn fmt(&self, f:&mut std::fmt::Formatter<'_>)->std::fmt::Result {{ f.write_str("maintenance service request failed") }} }}
impl std::error::Error for MaintenanceServiceClientFailure {{}}
pub struct MaintenanceServiceClient {{ endpoint:String, client:reqwest::blocking::Client }}
impl MaintenanceServiceClient {{
pub fn new(transport:super::MaintenanceTransport)->Result<Self,MaintenanceServiceClientFailure>{{let(endpoint,builder)=match transport{{super::MaintenanceTransport::PlaintextOptOut{{endpoint}}=>(format!("http://{{endpoint}}"),reqwest::blocking::Client::builder()),super::MaintenanceTransport::Tls{{endpoint,server_name,trust_file}}=>{{let ip=server_name.parse::<std::net::IpAddr>();if server_name.is_empty()||server_name.len()>253||ip.as_ref().is_ok_and(|ip|*ip!=endpoint.ip()){{return Err(MaintenanceServiceClientFailure::Transport)}}let trust=std::fs::read(trust_file).map_err(|_|MaintenanceServiceClientFailure::Transport)?;let certificate=reqwest::Certificate::from_pem(&trust).map_err(|_|MaintenanceServiceClientFailure::Transport)?;let authority=match ip{{Ok(std::net::IpAddr::V6(_))=>format!("[{{server_name}}]"),_=>server_name.clone()}};(format!("https://{{authority}}:{{}}",endpoint.port()),reqwest::blocking::Client::builder().add_root_certificate(certificate).resolve(&server_name,endpoint))}}}};Ok(Self{{endpoint,client:builder.connect_timeout(Duration::from_secs(5)).timeout(Duration::from_secs(5)).no_proxy().build().map_err(|_|MaintenanceServiceClientFailure::Transport)?}})}}
pub fn status(&self,bearer:&str,request:&super::MaintenanceStatusRequest)->Result<super::MaintenanceStatusResponse,MaintenanceServiceClientFailure>{{let body=serde_json::to_vec(request).map_err(|_|MaintenanceServiceClientFailure::InvalidRequest)?;if body.len()>{request_limit}{{return Err(MaintenanceServiceClientFailure::InvalidRequest)}}let response=self.client.post(format!("{{}}{{}}",self.endpoint,{path:?})).bearer_auth(bearer).header(reqwest::header::CONTENT_TYPE,"application/json").body(body).send().map_err(|_|MaintenanceServiceClientFailure::Transport)?;let status=response.status().as_u16();let mut bytes=Vec::with_capacity({response_limit});response.take(({response_limit}+1)as u64).read_to_end(&mut bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)?;if bytes.len()>{response_limit}{{return Err(MaintenanceServiceClientFailure::Transport)}}
if !(200..300).contains(&status){{let code=serde_json::from_slice::<serde_json::Value>(&bytes).ok().and_then(|value|value.get("code")?.as_str().map(str::to_owned));return Err(match(status,code.as_deref()){{(400,Some("invalid_request"))=>MaintenanceServiceClientFailure::InvalidRequest,(401,Some("authentication_rejected"))=>MaintenanceServiceClientFailure::AuthenticationRejected,(503,Some("administration_unavailable"))=>MaintenanceServiceClientFailure::AdministrationUnavailable,_=>MaintenanceServiceClientFailure::Transport}})}}super::MaintenanceStatusResponse::decode(&bytes).map_err(|_|MaintenanceServiceClientFailure::Transport)}}
}}
"#
    );
    write_generated("maintenance_service_client.rs", source)
}
